-- PerkCommons Next fork: greenfield Supabase baseline
-- Generated by scripts/build-greenfield-migration.mjs.
--
-- EMPTY PROJECTS ONLY. Do not apply this file after the incremental migrations.
-- It creates private submission/moderation state. It does not create users,
-- credentials, storage buckets, Cloudflare resources, or GitHub integrations.

begin;

do $preflight$
begin
  if to_regclass('auth.users') is null then
    raise exception 'PerkCommons baseline requires a Supabase project with auth.users';
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role')
     or not exists (select 1 from pg_roles where rolname = 'authenticated')
     or not exists (select 1 from pg_roles where rolname = 'anon') then
    raise exception 'PerkCommons baseline requires Supabase API roles';
  end if;
  if to_regclass('public.opportunity_submissions') is not null then
    raise exception 'PerkCommons greenfield baseline requires an empty public application schema';
  end if;
end
$preflight$;

create extension if not exists pgcrypto;

create table public.opportunity_submissions (
  id uuid primary key default gen_random_uuid(),
  organization text not null,
  name text not null,
  categories text[] not null default '{}',
  source_url text not null,
  website_url text not null,
  description text not null,
  eligibility text not null,
  location text,
  deadline date,
  submitter_name text,
  submitter_email text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- --------------------------------------------------------------------------
-- Squashed from supabase/migrations/202607170001_moderation_system.sql
-- --------------------------------------------------------------------------
create extension if not exists pgcrypto;

do $$
begin
  alter type public.submission_status add value if not exists 'reviewing';
  alter type public.submission_status add value if not exists 'withdrawn';
exception
  when undefined_object then null;
end $$;

-- The Worker is now the only submission writer. Remove legacy browser policies
-- before changing status because PostgreSQL policies can depend on its type.
do $$
declare
  policy_record record;
begin
  for policy_record in
    select policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'opportunity_submissions'
  loop
    execute format(
      'drop policy if exists %I on public.opportunity_submissions',
      policy_record.policyname
    );
  end loop;
end $$;

alter table public.opportunity_submissions
  drop constraint if exists opportunity_submissions_status_check;
alter table public.opportunity_submissions
  alter column status drop default;
alter table public.opportunity_submissions
  alter column status type text using status::text;
alter table public.opportunity_submissions
  alter column status set default 'pending';

alter table public.opportunity_submissions
  add column if not exists benefits text,
  add column if not exists organization_website_url text,
  add column if not exists submitter_notes text,
  add column if not exists reviewed_by uuid references auth.users(id) on delete set null,
  add column if not exists decision_reason text,
  add column if not exists risk_score numeric(5, 2) not null default 0,
  add column if not exists flag_count integer not null default 0,
  add column if not exists submission_ip_hash text,
  add column if not exists submission_email_hash text,
  add column if not exists submission_country_code varchar(2),
  add column if not exists submission_user_agent_hash text,
  add column if not exists last_action_at timestamptz,
  add column if not exists reviewed_at timestamptz,
  add column if not exists published_at timestamptz;

alter table public.opportunity_submissions
  add constraint opportunity_submissions_status_check
  check (status::text in ('pending', 'reviewing', 'flagged', 'approved', 'rejected', 'published', 'withdrawn'));
alter table public.opportunity_submissions
  drop constraint if exists opportunity_submissions_country_code_check;
alter table public.opportunity_submissions
  add constraint opportunity_submissions_country_code_check
  check (submission_country_code is null or submission_country_code ~ '^[A-Z]{2}$');

create table if not exists public.moderator_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('reviewer', 'admin')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.normalized_opportunities (
  submission_id uuid primary key references public.opportunity_submissions(id) on delete cascade,
  title text not null,
  organization text not null,
  categories text[] not null default '{}',
  description text not null,
  eligibility text not null,
  benefits text,
  location text,
  deadline date,
  source_url text not null,
  organization_website_url text,
  normalized_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moderation_actions (
  id uuid primary key default gen_random_uuid(),
  submission_id uuid references public.opportunity_submissions(id) on delete set null,
  moderator_id uuid not null references auth.users(id),
  action text not null,
  reason text,
  notes text,
  previous_status text,
  new_status text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.submission_flags (
  id uuid primary key default gen_random_uuid(),
  submission_id uuid not null references public.opportunity_submissions(id) on delete cascade,
  reason text not null,
  notes text,
  moderator_id uuid not null references auth.users(id),
  resolved boolean not null default false,
  resolved_by uuid references auth.users(id),
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.listing_reports (
  id uuid primary key default gen_random_uuid(),
  listing_id text not null,
  reason text not null,
  details text,
  reporter_email text,
  reporter_email_hash text,
  reporter_ip_hash text,
  reporter_country_code varchar(2),
  status text not null default 'open' check (status in ('open', 'reviewing', 'resolved', 'dismissed')),
  assigned_to uuid references auth.users(id),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.moderation_bans (
  id uuid primary key default gen_random_uuid(),
  identifier_type text not null check (identifier_type in ('email', 'ip')),
  identifier_hash text not null,
  display_hint text not null,
  reason text not null,
  notes text,
  mode text not null default 'block' check (mode in ('block', 'flag', 'warn')),
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  expires_at timestamptz,
  active boolean not null default true
);

create table if not exists public.submission_fingerprints (
  id uuid primary key default gen_random_uuid(),
  submission_id uuid not null references public.opportunity_submissions(id) on delete cascade,
  email_hash text,
  ip_hash text,
  user_agent_hash text,
  country_code varchar(2),
  created_at timestamptz not null default now(),
  unique (submission_id)
);

create index if not exists opportunity_submissions_moderation_queue
  on public.opportunity_submissions (status, created_at);
create index if not exists moderation_actions_submission_created
  on public.moderation_actions (submission_id, created_at desc);
create index if not exists submission_flags_active
  on public.submission_flags (submission_id, resolved, created_at desc);
create index if not exists listing_reports_queue
  on public.listing_reports (status, created_at);
create index if not exists moderation_bans_lookup
  on public.moderation_bans (identifier_type, identifier_hash, active, expires_at);
create unique index if not exists moderation_bans_one_active_identifier
  on public.moderation_bans (identifier_type, identifier_hash) where active = true;
create index if not exists submission_fingerprints_email
  on public.submission_fingerprints (email_hash) where email_hash is not null;
create index if not exists submission_fingerprints_ip
  on public.submission_fingerprints (ip_hash) where ip_hash is not null;

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists moderator_profiles_touch_updated_at on public.moderator_profiles;
create trigger moderator_profiles_touch_updated_at before update on public.moderator_profiles
for each row execute function public.touch_updated_at();
drop trigger if exists normalized_opportunities_touch_updated_at on public.normalized_opportunities;
create trigger normalized_opportunities_touch_updated_at before update on public.normalized_opportunities
for each row execute function public.touch_updated_at();

create or replace function public.perform_moderation_action(
  p_submission_id uuid,
  p_moderator_id uuid,
  p_action text,
  p_reason text default null,
  p_notes text default null,
  p_normalized jsonb default null
) returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role text;
  v_previous text;
  v_next text;
  v_action_id uuid;
begin
  select role into v_role from public.moderator_profiles
  where user_id = p_moderator_id and active = true;
  if v_role is null then raise exception 'moderator access required'; end if;

  select status::text into v_previous from public.opportunity_submissions
  where id = p_submission_id for update;
  if v_previous is null then raise exception 'submission not found'; end if;

  v_next := case p_action
    when 'approve' then 'approved'
    when 'decline' then 'rejected'
    when 'flag' then 'flagged'
    when 'unflag' then 'pending'
    when 'publish' then 'published'
    when 'withdraw' then 'withdrawn'
    else v_previous
  end;

  if p_action not in ('approve', 'decline', 'flag', 'unflag', 'publish', 'withdraw', 'note', 'edit') then
    raise exception 'unsupported moderation action';
  end if;

  update public.opportunity_submissions
  set status = v_next,
      reviewed_by = p_moderator_id,
      decision_reason = case when p_action in ('approve', 'decline') then p_reason else decision_reason end,
      reviewed_at = case when p_action in ('approve', 'decline') then now() else reviewed_at end,
      published_at = case when p_action = 'publish' then now() else published_at end,
      last_action_at = now(),
      flag_count = case when p_action = 'flag' then flag_count + 1 when p_action = 'unflag' then 0 else flag_count end
  where id = p_submission_id;

  if p_action = 'flag' then
    insert into public.submission_flags (submission_id, reason, notes, moderator_id)
    values (p_submission_id, coalesce(p_reason, 'Other'), p_notes, p_moderator_id);
  elsif p_action = 'unflag' then
    update public.submission_flags
    set resolved = true, resolved_by = p_moderator_id, resolved_at = now()
    where submission_id = p_submission_id and resolved = false;
  end if;

  if p_action = 'approve' and p_normalized is not null then
    insert into public.normalized_opportunities (
      submission_id, title, organization, categories, description, eligibility,
      benefits, location, deadline, source_url, organization_website_url, normalized_by
    ) values (
      p_submission_id, p_normalized->>'title', p_normalized->>'organization',
      coalesce(array(select jsonb_array_elements_text(p_normalized->'categories')), '{}'),
      p_normalized->>'description', p_normalized->>'eligibility', p_normalized->>'benefits',
      p_normalized->>'location', nullif(p_normalized->>'deadline', '')::date,
      p_normalized->>'source_url', p_normalized->>'organization_website_url', p_moderator_id
    ) on conflict (submission_id) do update set
      title = excluded.title, organization = excluded.organization, categories = excluded.categories,
      description = excluded.description, eligibility = excluded.eligibility, benefits = excluded.benefits,
      location = excluded.location, deadline = excluded.deadline, source_url = excluded.source_url,
      organization_website_url = excluded.organization_website_url,
      normalized_by = excluded.normalized_by, updated_at = now();
  end if;

  insert into public.moderation_actions (
    submission_id, moderator_id, action, reason, notes, previous_status, new_status,
    metadata
  ) values (
    p_submission_id, p_moderator_id, p_action, p_reason, p_notes, v_previous, v_next,
    case when p_normalized is null then '{}'::jsonb else jsonb_build_object('normalized_fields', true) end
  ) returning id into v_action_id;

  return v_action_id;
end;
$$;

create or replace function public.undo_moderation_action(
  p_submission_id uuid,
  p_moderator_id uuid
) returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role text;
  v_last public.moderation_actions%rowtype;
  v_current text;
  v_action_id uuid;
begin
  select role into v_role from public.moderator_profiles
  where user_id = p_moderator_id and active = true;
  if v_role is null then raise exception 'moderator access required'; end if;

  select * into v_last from public.moderation_actions
  where submission_id = p_submission_id and action in ('approve', 'decline', 'flag', 'unflag')
  order by created_at desc limit 1;
  if v_last.id is null then raise exception 'nothing to undo'; end if;
  if v_last.created_at < now() - interval '10 minutes' then raise exception 'undo window expired'; end if;

  select status::text into v_current from public.opportunity_submissions
  where id = p_submission_id for update;

  if v_last.action = 'flag' then
    with latest_flag as (
      select id from public.submission_flags
      where submission_id = p_submission_id and moderator_id = v_last.moderator_id
        and resolved = false and created_at between v_last.created_at - interval '5 seconds' and v_last.created_at + interval '5 seconds'
      order by created_at desc limit 1
    )
    update public.submission_flags set resolved = true, resolved_by = p_moderator_id, resolved_at = now()
    where id in (select id from latest_flag);
  elsif v_last.action = 'unflag' then
    update public.submission_flags set resolved = false, resolved_by = null, resolved_at = null
    where submission_id = p_submission_id and resolved_by = v_last.moderator_id
      and resolved_at between v_last.created_at - interval '5 seconds' and v_last.created_at + interval '5 seconds';
  end if;

  update public.opportunity_submissions
  set status = v_last.previous_status,
      decision_reason = case when v_last.action in ('approve', 'decline') then null else decision_reason end,
      reviewed_at = case when v_last.action in ('approve', 'decline') then null else reviewed_at end,
      flag_count = (select count(*)::integer from public.submission_flags where submission_id = p_submission_id and resolved = false),
      last_action_at = now()
  where id = p_submission_id;

  insert into public.moderation_actions (
    submission_id, moderator_id, action, reason, previous_status, new_status, metadata
  ) values (
    p_submission_id, p_moderator_id, 'undo', 'Moderator undo', v_current,
    v_last.previous_status, jsonb_build_object('undone_action_id', v_last.id)
  ) returning id into v_action_id;
  return v_action_id;
end;
$$;

create or replace function public.create_moderation_ban(
  p_submission_id uuid,
  p_moderator_id uuid,
  p_identifier_type text,
  p_identifier_hash text,
  p_display_hint text,
  p_reason text,
  p_notes text,
  p_mode text,
  p_expires_at timestamptz
) returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role text;
  v_ban_id uuid;
begin
  select role into v_role from public.moderator_profiles
  where user_id = p_moderator_id and active = true;
  if v_role is distinct from 'admin' then raise exception 'administrator access required'; end if;
  if p_identifier_type not in ('email', 'ip') or p_mode not in ('block', 'flag', 'warn') then
    raise exception 'invalid abuse control';
  end if;

  insert into public.moderation_bans (
    identifier_type, identifier_hash, display_hint, reason, notes, mode,
    created_by, expires_at
  ) values (
    p_identifier_type, p_identifier_hash, p_display_hint, p_reason, p_notes,
    p_mode, p_moderator_id, p_expires_at
  ) returning id into v_ban_id;

  insert into public.moderation_actions (
    submission_id, moderator_id, action, reason, notes, metadata
  ) values (
    p_submission_id, p_moderator_id, 'ban', p_reason, p_notes,
    jsonb_build_object('ban_id', v_ban_id, 'identifier_type', p_identifier_type, 'mode', p_mode, 'expires_at', p_expires_at)
  );
  return v_ban_id;
end;
$$;

create or replace function public.disable_moderation_ban(
  p_ban_id uuid,
  p_moderator_id uuid
) returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role text;
  v_action_id uuid;
begin
  select role into v_role from public.moderator_profiles
  where user_id = p_moderator_id and active = true;
  if v_role is distinct from 'admin' then raise exception 'administrator access required'; end if;

  update public.moderation_bans set active = false
  where id = p_ban_id and active = true;
  if not found then raise exception 'active abuse control not found'; end if;

  insert into public.moderation_actions (moderator_id, action, reason, metadata)
  values (p_moderator_id, 'unban', 'Administrator removed abuse control', jsonb_build_object('ban_id', p_ban_id))
  returning id into v_action_id;
  return v_action_id;
end;
$$;

create or replace function public.create_submission_bans(
  p_submission_id uuid,
  p_moderator_id uuid,
  p_identifier_type text,
  p_email_hash text,
  p_ip_hash text,
  p_email_hint text,
  p_ip_hint text,
  p_reason text,
  p_notes text,
  p_mode text,
  p_expires_at timestamptz
) returns uuid[]
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role text;
  v_type text;
  v_hash text;
  v_hint text;
  v_ban_id uuid;
  v_ids uuid[] := '{}';
begin
  select role into v_role from public.moderator_profiles
  where user_id = p_moderator_id and active = true;
  if v_role is distinct from 'admin' then raise exception 'administrator access required'; end if;
  if p_identifier_type not in ('email', 'ip', 'both') or p_mode not in ('block', 'flag', 'warn') then
    raise exception 'invalid abuse control';
  end if;

  foreach v_type in array case p_identifier_type when 'both' then array['email', 'ip'] else array[p_identifier_type] end
  loop
    v_hash := case v_type when 'email' then p_email_hash else p_ip_hash end;
    v_hint := case v_type when 'email' then p_email_hint else p_ip_hint end;
    if v_hash is null then raise exception 'fingerprint unavailable'; end if;
    insert into public.moderation_bans (
      identifier_type, identifier_hash, display_hint, reason, notes, mode,
      created_by, expires_at
    ) values (
      v_type, v_hash, v_hint, p_reason, p_notes, p_mode, p_moderator_id, p_expires_at
    ) returning id into v_ban_id;
    v_ids := array_append(v_ids, v_ban_id);
    insert into public.moderation_actions (
      submission_id, moderator_id, action, reason, notes, metadata
    ) values (
      p_submission_id, p_moderator_id, 'ban', p_reason, p_notes,
      jsonb_build_object('ban_id', v_ban_id, 'identifier_type', v_type, 'mode', p_mode, 'expires_at', p_expires_at)
    );
  end loop;
  return v_ids;
end;
$$;

alter table public.opportunity_submissions enable row level security;
alter table public.moderator_profiles enable row level security;
alter table public.normalized_opportunities enable row level security;
alter table public.moderation_actions enable row level security;
alter table public.submission_flags enable row level security;
alter table public.listing_reports enable row level security;
alter table public.moderation_bans enable row level security;
alter table public.submission_fingerprints enable row level security;

revoke all on public.opportunity_submissions, public.moderator_profiles, public.normalized_opportunities,
  public.moderation_actions, public.submission_flags, public.listing_reports,
  public.moderation_bans, public.submission_fingerprints from anon, authenticated;
revoke execute on function public.perform_moderation_action(uuid, uuid, text, text, text, jsonb) from public, anon, authenticated;
revoke execute on function public.undo_moderation_action(uuid, uuid) from public, anon, authenticated;
revoke execute on function public.create_moderation_ban(uuid, uuid, text, text, text, text, text, text, timestamptz) from public, anon, authenticated;
revoke execute on function public.disable_moderation_ban(uuid, uuid) from public, anon, authenticated;
revoke execute on function public.create_submission_bans(uuid, uuid, text, text, text, text, text, text, text, text, timestamptz) from public, anon, authenticated;
grant execute on function public.perform_moderation_action(uuid, uuid, text, text, text, jsonb) to service_role;
grant execute on function public.undo_moderation_action(uuid, uuid) to service_role;
grant execute on function public.create_moderation_ban(uuid, uuid, text, text, text, text, text, text, timestamptz) to service_role;
grant execute on function public.disable_moderation_ban(uuid, uuid) to service_role;
grant execute on function public.create_submission_bans(uuid, uuid, text, text, text, text, text, text, text, text, timestamptz) to service_role;

-- --------------------------------------------------------------------------
-- Squashed from supabase/migrations/202607170002_moderation_retention.sql
-- --------------------------------------------------------------------------
create extension if not exists pg_cron with schema pg_catalog;

create table if not exists public.moderation_retention_runs (
  id bigint generated always as identity primary key,
  ran_at timestamptz not null default now(),
  results jsonb not null
);

alter table public.moderation_retention_runs enable row level security;
revoke all on public.moderation_retention_runs from public, anon, authenticated;

create or replace function public.apply_moderation_retention(
  p_now timestamptz default now()
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  v_expired_bans integer := 0;
  v_fingerprints_deleted integer := 0;
  v_submissions_redacted integer := 0;
  v_reports_redacted integer := 0;
  v_action_notes_redacted integer := 0;
  v_flag_notes_redacted integer := 0;
  v_ban_notes_redacted integer := 0;
  v_report_details_redacted integer := 0;
  v_temporary_bans_deleted integer := 0;
  v_old_actions_deleted integer := 0;
  v_old_flags_deleted integer := 0;
  v_old_reports_deleted integer := 0;
  v_stale_active_submissions integer := 0;
  v_permanent_bans_due_review integer := 0;
  v_results jsonb;
begin
  update public.moderation_bans
  set active = false
  where active = true
    and expires_at is not null
    and expires_at <= p_now;
  get diagnostics v_expired_bans = row_count;

  delete from public.submission_fingerprints as fingerprints
  using public.opportunity_submissions as submissions
  where fingerprints.submission_id = submissions.id
    and submissions.status in ('rejected', 'withdrawn', 'published')
    and coalesce(
      submissions.published_at,
      submissions.reviewed_at,
      submissions.last_action_at,
      submissions.created_at
    ) < p_now - interval '90 days';
  get diagnostics v_fingerprints_deleted = row_count;

  update public.opportunity_submissions
  set submitter_name = null,
      submitter_email = null,
      submitter_notes = null,
      submission_ip_hash = null,
      submission_email_hash = null,
      submission_country_code = null,
      submission_user_agent_hash = null
  where status in ('rejected', 'withdrawn', 'published')
    and coalesce(published_at, reviewed_at, last_action_at, created_at)
      < p_now - interval '90 days'
    and (
      submitter_name is not null
      or submitter_email is not null
      or submitter_notes is not null
      or submission_ip_hash is not null
      or submission_email_hash is not null
      or submission_country_code is not null
      or submission_user_agent_hash is not null
    );
  get diagnostics v_submissions_redacted = row_count;

  update public.listing_reports
  set reporter_email = null,
      reporter_email_hash = null,
      reporter_ip_hash = null,
      reporter_country_code = null
  where status in ('resolved', 'dismissed')
    and coalesce(resolved_at, created_at) < p_now - interval '90 days'
    and (
      reporter_email is not null
      or reporter_email_hash is not null
      or reporter_ip_hash is not null
      or reporter_country_code is not null
    );
  get diagnostics v_reports_redacted = row_count;

  update public.moderation_actions
  set notes = null
  where notes is not null
    and created_at < p_now - interval '1 year';
  get diagnostics v_action_notes_redacted = row_count;

  update public.submission_flags
  set notes = null
  where notes is not null
    and created_at < p_now - interval '1 year';
  get diagnostics v_flag_notes_redacted = row_count;

  update public.moderation_bans
  set notes = null
  where notes is not null
    and created_at < p_now - interval '1 year';
  get diagnostics v_ban_notes_redacted = row_count;

  update public.listing_reports
  set details = null
  where details is not null
    and status in ('resolved', 'dismissed')
    and coalesce(resolved_at, created_at) < p_now - interval '1 year';
  get diagnostics v_report_details_redacted = row_count;

  delete from public.moderation_bans
  where active = false
    and expires_at is not null
    and expires_at < p_now - interval '90 days';
  get diagnostics v_temporary_bans_deleted = row_count;

  delete from public.submission_flags
  where resolved = true
    and coalesce(resolved_at, created_at) < p_now - interval '3 years';
  get diagnostics v_old_flags_deleted = row_count;

  delete from public.listing_reports
  where status in ('resolved', 'dismissed')
    and coalesce(resolved_at, created_at) < p_now - interval '3 years';
  get diagnostics v_old_reports_deleted = row_count;

  delete from public.moderation_actions
  where created_at < p_now - interval '3 years';
  get diagnostics v_old_actions_deleted = row_count;

  select count(*)::integer
  into v_stale_active_submissions
  from public.opportunity_submissions
  where status in ('pending', 'reviewing', 'flagged')
    and created_at < p_now - interval '180 days';

  select count(*)::integer
  into v_permanent_bans_due_review
  from public.moderation_bans
  where active = true
    and expires_at is null
    and created_at < p_now - interval '1 year';

  v_results := jsonb_build_object(
    'expired_bans', v_expired_bans,
    'fingerprints_deleted', v_fingerprints_deleted,
    'submissions_redacted', v_submissions_redacted,
    'reports_redacted', v_reports_redacted,
    'action_notes_redacted', v_action_notes_redacted,
    'flag_notes_redacted', v_flag_notes_redacted,
    'ban_notes_redacted', v_ban_notes_redacted,
    'report_details_redacted', v_report_details_redacted,
    'temporary_bans_deleted', v_temporary_bans_deleted,
    'old_actions_deleted', v_old_actions_deleted,
    'old_flags_deleted', v_old_flags_deleted,
    'old_reports_deleted', v_old_reports_deleted,
    'stale_active_submissions', v_stale_active_submissions,
    'permanent_bans_due_review', v_permanent_bans_due_review
  );

  delete from public.moderation_retention_runs
  where ran_at < p_now - interval '1 year';

  insert into public.moderation_retention_runs (ran_at, results)
  values (p_now, v_results);

  return v_results;
end;
$$;

revoke execute on function public.apply_moderation_retention(timestamptz)
  from public, anon, authenticated;
grant execute on function public.apply_moderation_retention(timestamptz)
  to service_role;

do $$
declare
  existing_job record;
begin
  for existing_job in
    select jobid
    from cron.job
    where jobname = 'perkcommons-moderation-retention'
  loop
    perform cron.unschedule(existing_job.jobid);
  end loop;

  perform cron.schedule(
    'perkcommons-moderation-retention',
    '23 3 * * *',
    'select public.apply_moderation_retention();'
  );
end $$;

-- --------------------------------------------------------------------------
-- Squashed from supabase/migrations/202607170003_submission_website_compatibility.sql
-- --------------------------------------------------------------------------
-- Preserve legacy organization URLs, then make the old column optional. The
-- Worker continues writing it during rollout so this migration is not required
-- for uninterrupted submissions.
update public.opportunity_submissions
set organization_website_url = website_url
where organization_website_url is null
  and website_url is not null;

alter table public.opportunity_submissions
  alter column website_url drop not null;

-- --------------------------------------------------------------------------
-- Squashed from supabase/migrations/202607180001_opportunity_taxonomy.sql
-- --------------------------------------------------------------------------
alter table public.opportunity_submissions
  add column if not exists primary_category text,
  add column if not exists subcategories text[] not null default '{}',
  add column if not exists tags text[] not null default '{}';

alter table public.normalized_opportunities
  add column if not exists primary_category text,
  add column if not exists subcategories text[] not null default '{}',
  add column if not exists tags text[] not null default '{}';

update public.opportunity_submissions
set primary_category = case coalesce(primary_category, categories[1])
  when 'ai-credits' then 'startup-benefits'
  when 'cloud-credits' then 'startup-benefits'
  when 'startup-programs' then 'startup-benefits'
  when 'grants' then 'funding'
  when 'discounts' then 'discounts-perks'
  when 'accelerators' then 'accelerators-incubators'
  when 'business-perks' then 'startup-benefits'
  else coalesce(primary_category, categories[1])
end
where primary_category is null
   or primary_category in ('ai-credits', 'cloud-credits', 'startup-programs', 'grants', 'discounts', 'accelerators', 'business-perks');

update public.normalized_opportunities
set primary_category = case coalesce(primary_category, categories[1])
  when 'ai-credits' then 'startup-benefits'
  when 'cloud-credits' then 'startup-benefits'
  when 'startup-programs' then 'startup-benefits'
  when 'grants' then 'funding'
  when 'discounts' then 'discounts-perks'
  when 'accelerators' then 'accelerators-incubators'
  when 'business-perks' then 'startup-benefits'
  else coalesce(primary_category, categories[1])
end
where primary_category is null
   or primary_category in ('ai-credits', 'cloud-credits', 'startup-programs', 'grants', 'discounts', 'accelerators', 'business-perks');

alter table public.opportunity_submissions
  drop constraint if exists opportunity_submissions_primary_category_check,
  drop constraint if exists opportunity_submissions_subcategories_count_check,
  drop constraint if exists opportunity_submissions_tags_count_check;
alter table public.opportunity_submissions
  add constraint opportunity_submissions_primary_category_check check (
    primary_category is null or primary_category in (
      'startup-benefits', 'student-benefits', 'nonprofit-benefits',
      'developer-programs', 'funding', 'accelerators-incubators',
      'competitions-hackathons', 'fellowships', 'internships-work-experience',
      'research-opportunities', 'mentorship-community', 'education-training',
      'open-source', 'social-impact-civic-tech', 'creator-media',
      'events-conferences', 'discounts-perks', 'volunteer-service',
      'awards-recognition', 'early-access'
    )
  ),
  add constraint opportunity_submissions_subcategories_count_check check (cardinality(subcategories) <= 8),
  add constraint opportunity_submissions_tags_count_check check (cardinality(tags) <= 12);

alter table public.normalized_opportunities
  drop constraint if exists normalized_opportunities_primary_category_check,
  drop constraint if exists normalized_opportunities_subcategories_count_check,
  drop constraint if exists normalized_opportunities_tags_count_check;
alter table public.normalized_opportunities
  add constraint normalized_opportunities_primary_category_check check (
    primary_category is null or primary_category in (
      'startup-benefits', 'student-benefits', 'nonprofit-benefits',
      'developer-programs', 'funding', 'accelerators-incubators',
      'competitions-hackathons', 'fellowships', 'internships-work-experience',
      'research-opportunities', 'mentorship-community', 'education-training',
      'open-source', 'social-impact-civic-tech', 'creator-media',
      'events-conferences', 'discounts-perks', 'volunteer-service',
      'awards-recognition', 'early-access'
    )
  ),
  add constraint normalized_opportunities_subcategories_count_check check (cardinality(subcategories) <= 8),
  add constraint normalized_opportunities_tags_count_check check (cardinality(tags) <= 12);

create index if not exists opportunity_submissions_category_queue
  on public.opportunity_submissions (primary_category, status, created_at);

create or replace function public.perform_moderation_action(
  p_submission_id uuid,
  p_moderator_id uuid,
  p_action text,
  p_reason text default null,
  p_notes text default null,
  p_normalized jsonb default null
) returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role text;
  v_previous text;
  v_next text;
  v_action_id uuid;
begin
  select role into v_role from public.moderator_profiles
  where user_id = p_moderator_id and active = true;
  if v_role is null then raise exception 'moderator access required'; end if;

  select status::text into v_previous from public.opportunity_submissions
  where id = p_submission_id for update;
  if v_previous is null then raise exception 'submission not found'; end if;

  v_next := case p_action
    when 'approve' then 'approved'
    when 'decline' then 'rejected'
    when 'flag' then 'flagged'
    when 'unflag' then 'pending'
    when 'publish' then 'published'
    when 'withdraw' then 'withdrawn'
    else v_previous
  end;

  if p_action not in ('approve', 'decline', 'flag', 'unflag', 'publish', 'withdraw', 'note', 'edit') then
    raise exception 'unsupported moderation action';
  end if;

  update public.opportunity_submissions
  set status = v_next,
      reviewed_by = p_moderator_id,
      decision_reason = case when p_action in ('approve', 'decline') then p_reason else decision_reason end,
      reviewed_at = case when p_action in ('approve', 'decline') then now() else reviewed_at end,
      published_at = case when p_action = 'publish' then now() else published_at end,
      last_action_at = now(),
      flag_count = case when p_action = 'flag' then flag_count + 1 when p_action = 'unflag' then 0 else flag_count end
  where id = p_submission_id;

  if p_action = 'flag' then
    insert into public.submission_flags (submission_id, reason, notes, moderator_id)
    values (p_submission_id, coalesce(p_reason, 'Other'), p_notes, p_moderator_id);
  elsif p_action = 'unflag' then
    update public.submission_flags
    set resolved = true, resolved_by = p_moderator_id, resolved_at = now()
    where submission_id = p_submission_id and resolved = false;
  end if;

  if p_action = 'approve' and p_normalized is not null then
    insert into public.normalized_opportunities (
      submission_id, title, organization, categories, primary_category,
      subcategories, tags, description, eligibility, benefits, location,
      deadline, source_url, organization_website_url, normalized_by
    ) values (
      p_submission_id, p_normalized->>'title', p_normalized->>'organization',
      coalesce(array(select jsonb_array_elements_text(p_normalized->'categories')), '{}'),
      p_normalized->>'primary_category',
      coalesce(array(select jsonb_array_elements_text(p_normalized->'subcategories')), '{}'),
      coalesce(array(select jsonb_array_elements_text(p_normalized->'tags')), '{}'),
      p_normalized->>'description', p_normalized->>'eligibility', p_normalized->>'benefits',
      p_normalized->>'location', nullif(p_normalized->>'deadline', '')::date,
      p_normalized->>'source_url', p_normalized->>'organization_website_url', p_moderator_id
    ) on conflict (submission_id) do update set
      title = excluded.title,
      organization = excluded.organization,
      categories = excluded.categories,
      primary_category = excluded.primary_category,
      subcategories = excluded.subcategories,
      tags = excluded.tags,
      description = excluded.description,
      eligibility = excluded.eligibility,
      benefits = excluded.benefits,
      location = excluded.location,
      deadline = excluded.deadline,
      source_url = excluded.source_url,
      organization_website_url = excluded.organization_website_url,
      normalized_by = excluded.normalized_by,
      updated_at = now();
  end if;

  insert into public.moderation_actions (
    submission_id, moderator_id, action, reason, notes, previous_status, new_status,
    metadata
  ) values (
    p_submission_id, p_moderator_id, p_action, p_reason, p_notes, v_previous, v_next,
    case when p_normalized is null then '{}'::jsonb else jsonb_build_object('normalized_fields', true) end
  ) returning id into v_action_id;

  return v_action_id;
end;
$$;

revoke execute on function public.perform_moderation_action(uuid, uuid, text, text, text, jsonb)
  from public, anon, authenticated;
grant execute on function public.perform_moderation_action(uuid, uuid, text, text, text, jsonb)
  to service_role;

-- --------------------------------------------------------------------------
-- Squashed from supabase/migrations/202607190001_moderation_workspace.sql
-- --------------------------------------------------------------------------
alter table public.listing_reports
  add column if not exists resolution_notes text;
alter table public.listing_reports
  drop constraint if exists listing_reports_status_check;
update public.listing_reports
set status = 'dismissed'
where status = 'resolved';
alter table public.listing_reports
  add constraint listing_reports_status_check
  check (status in ('open', 'reviewing', 'upheld', 'dismissed'));

create table if not exists public.listing_moderation_state (
  listing_id text primary key check (listing_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  featured boolean not null default false,
  removed boolean not null default false,
  removal_report_id uuid references public.listing_reports(id) on delete set null,
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists listing_moderation_state_touch_updated_at
  on public.listing_moderation_state;
create trigger listing_moderation_state_touch_updated_at
before update on public.listing_moderation_state
for each row execute function public.touch_updated_at();

create or replace function public.resolve_listing_report(
  p_report_id uuid,
  p_moderator_id uuid,
  p_decision text,
  p_notes text default null
) returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_listing_id text;
begin
  if not exists (
    select 1 from public.moderator_profiles
    where user_id = p_moderator_id and active = true
  ) then
    raise exception 'moderator access required';
  end if;
  if p_decision not in ('upheld', 'dismissed') then
    raise exception 'invalid report decision';
  end if;

  select listing_id into v_listing_id
  from public.listing_reports
  where id = p_report_id and status in ('open', 'reviewing')
  for update;
  if v_listing_id is null then raise exception 'open report not found'; end if;

  update public.listing_reports
  set status = p_decision,
      assigned_to = p_moderator_id,
      resolution_notes = nullif(trim(p_notes), ''),
      resolved_at = now()
  where id = p_report_id;

  if p_decision = 'upheld' then
    insert into public.listing_moderation_state (
      listing_id, removed, removal_report_id, updated_by
    ) values (
      v_listing_id, true, p_report_id, p_moderator_id
    ) on conflict (listing_id) do update set
      removed = true,
      removal_report_id = excluded.removal_report_id,
      updated_by = excluded.updated_by,
      updated_at = now();
  end if;

  insert into public.moderation_actions (
    moderator_id, action, reason, notes, metadata
  ) values (
    p_moderator_id,
    case when p_decision = 'upheld' then 'report_upheld' else 'report_dismissed' end,
    p_decision,
    nullif(trim(p_notes), ''),
    jsonb_build_object('report_id', p_report_id, 'listing_id', v_listing_id)
  );
  return v_listing_id;
end;
$$;

create or replace function public.set_listing_featured(
  p_listing_id text,
  p_moderator_id uuid,
  p_featured boolean
) returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1 from public.moderator_profiles
    where user_id = p_moderator_id and active = true
  ) then
    raise exception 'moderator access required';
  end if;
  if p_listing_id !~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' then
    raise exception 'invalid listing identifier';
  end if;

  insert into public.listing_moderation_state (
    listing_id, featured, updated_by
  ) values (
    p_listing_id, p_featured, p_moderator_id
  ) on conflict (listing_id) do update set
    featured = excluded.featured,
    updated_by = excluded.updated_by,
    updated_at = now();

  insert into public.moderation_actions (
    moderator_id, action, reason, metadata
  ) values (
    p_moderator_id,
    case when p_featured then 'listing_featured' else 'listing_unfeatured' end,
    case when p_featured then 'featured' else 'unfeatured' end,
    jsonb_build_object('listing_id', p_listing_id)
  );
end;
$$;

create or replace function public.purge_rejected_submissions(
  p_moderator_id uuid,
  p_submission_id uuid default null
) returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer;
begin
  if not exists (
    select 1 from public.moderator_profiles
    where user_id = p_moderator_id and active = true
  ) then
    raise exception 'moderator access required';
  end if;

  insert into public.moderation_actions (
    submission_id, moderator_id, action, reason, metadata
  )
  select id, p_moderator_id, 'rejected_submission_purged', 'storage cleanup',
    jsonb_build_object('submission_id', id, 'name', name, 'organization', organization)
  from public.opportunity_submissions
  where status = 'rejected'
    and (p_submission_id is null or id = p_submission_id);

  delete from public.opportunity_submissions
  where status = 'rejected'
    and (p_submission_id is null or id = p_submission_id);
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

create or replace function public.apply_moderation_retention(
  p_now timestamptz default now()
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  v_expired_bans integer := 0;
  v_fingerprints_deleted integer := 0;
  v_submissions_redacted integer := 0;
  v_reports_redacted integer := 0;
  v_action_notes_redacted integer := 0;
  v_flag_notes_redacted integer := 0;
  v_ban_notes_redacted integer := 0;
  v_report_details_redacted integer := 0;
  v_temporary_bans_deleted integer := 0;
  v_old_actions_deleted integer := 0;
  v_old_flags_deleted integer := 0;
  v_old_reports_deleted integer := 0;
  v_stale_active_submissions integer := 0;
  v_permanent_bans_due_review integer := 0;
  v_results jsonb;
begin
  update public.moderation_bans
  set active = false
  where active = true
    and expires_at is not null
    and expires_at <= p_now;
  get diagnostics v_expired_bans = row_count;

  delete from public.submission_fingerprints as fingerprints
  using public.opportunity_submissions as submissions
  where fingerprints.submission_id = submissions.id
    and submissions.status in ('rejected', 'withdrawn', 'published')
    and coalesce(
      submissions.published_at,
      submissions.reviewed_at,
      submissions.last_action_at,
      submissions.created_at
    ) < p_now - interval '90 days';
  get diagnostics v_fingerprints_deleted = row_count;

  update public.opportunity_submissions
  set submitter_name = null,
      submitter_email = null,
      submitter_notes = null,
      submission_ip_hash = null,
      submission_email_hash = null,
      submission_country_code = null,
      submission_user_agent_hash = null
  where status in ('rejected', 'withdrawn', 'published')
    and coalesce(published_at, reviewed_at, last_action_at, created_at)
      < p_now - interval '90 days'
    and (
      submitter_name is not null
      or submitter_email is not null
      or submitter_notes is not null
      or submission_ip_hash is not null
      or submission_email_hash is not null
      or submission_country_code is not null
      or submission_user_agent_hash is not null
    );
  get diagnostics v_submissions_redacted = row_count;

  update public.listing_reports
  set reporter_email = null,
      reporter_email_hash = null,
      reporter_ip_hash = null,
      reporter_country_code = null
  where status in ('upheld', 'dismissed')
    and coalesce(resolved_at, created_at) < p_now - interval '90 days'
    and (
      reporter_email is not null
      or reporter_email_hash is not null
      or reporter_ip_hash is not null
      or reporter_country_code is not null
    );
  get diagnostics v_reports_redacted = row_count;

  update public.moderation_actions
  set notes = null
  where notes is not null
    and created_at < p_now - interval '1 year';
  get diagnostics v_action_notes_redacted = row_count;

  update public.submission_flags
  set notes = null
  where notes is not null
    and created_at < p_now - interval '1 year';
  get diagnostics v_flag_notes_redacted = row_count;

  update public.moderation_bans
  set notes = null
  where notes is not null
    and created_at < p_now - interval '1 year';
  get diagnostics v_ban_notes_redacted = row_count;

  update public.listing_reports
  set details = null
  where details is not null
    and status in ('upheld', 'dismissed')
    and coalesce(resolved_at, created_at) < p_now - interval '1 year';
  get diagnostics v_report_details_redacted = row_count;

  delete from public.moderation_bans
  where active = false
    and expires_at is not null
    and expires_at < p_now - interval '90 days';
  get diagnostics v_temporary_bans_deleted = row_count;

  delete from public.submission_flags
  where resolved = true
    and coalesce(resolved_at, created_at) < p_now - interval '3 years';
  get diagnostics v_old_flags_deleted = row_count;

  delete from public.listing_reports
  where status in ('upheld', 'dismissed')
    and coalesce(resolved_at, created_at) < p_now - interval '3 years';
  get diagnostics v_old_reports_deleted = row_count;

  delete from public.moderation_actions
  where created_at < p_now - interval '3 years';
  get diagnostics v_old_actions_deleted = row_count;

  select count(*)::integer
  into v_stale_active_submissions
  from public.opportunity_submissions
  where status in ('pending', 'reviewing', 'flagged')
    and created_at < p_now - interval '180 days';

  select count(*)::integer
  into v_permanent_bans_due_review
  from public.moderation_bans
  where active = true
    and expires_at is null
    and created_at < p_now - interval '1 year';

  v_results := jsonb_build_object(
    'expired_bans', v_expired_bans,
    'fingerprints_deleted', v_fingerprints_deleted,
    'submissions_redacted', v_submissions_redacted,
    'reports_redacted', v_reports_redacted,
    'action_notes_redacted', v_action_notes_redacted,
    'flag_notes_redacted', v_flag_notes_redacted,
    'ban_notes_redacted', v_ban_notes_redacted,
    'report_details_redacted', v_report_details_redacted,
    'temporary_bans_deleted', v_temporary_bans_deleted,
    'old_actions_deleted', v_old_actions_deleted,
    'old_flags_deleted', v_old_flags_deleted,
    'old_reports_deleted', v_old_reports_deleted,
    'stale_active_submissions', v_stale_active_submissions,
    'permanent_bans_due_review', v_permanent_bans_due_review
  );

  delete from public.moderation_retention_runs
  where ran_at < p_now - interval '1 year';

  insert into public.moderation_retention_runs (ran_at, results)
  values (p_now, v_results);

  return v_results;
end;
$$;

alter table public.listing_moderation_state enable row level security;
revoke all on public.listing_moderation_state from anon, authenticated;
revoke execute on function public.resolve_listing_report(uuid, uuid, text, text)
  from public, anon, authenticated;
revoke execute on function public.set_listing_featured(text, uuid, boolean)
  from public, anon, authenticated;
revoke execute on function public.purge_rejected_submissions(uuid, uuid)
  from public, anon, authenticated;
revoke execute on function public.apply_moderation_retention(timestamptz)
  from public, anon, authenticated;
grant execute on function public.resolve_listing_report(uuid, uuid, text, text)
  to service_role;
grant execute on function public.set_listing_featured(text, uuid, boolean)
  to service_role;
grant execute on function public.purge_rejected_submissions(uuid, uuid)
  to service_role;
grant execute on function public.apply_moderation_retention(timestamptz)
  to service_role;

-- --------------------------------------------------------------------------
-- Squashed from supabase/migrations/202607190002_automated_publication.sql
-- --------------------------------------------------------------------------
create table public.publication_batches (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'preparing'
    check (status in ('preparing', 'validating', 'merging', 'published', 'failed')),
  created_by uuid not null references auth.users(id),
  item_count integer not null default 0 check (item_count >= 0),
  github_branch text,
  github_pr_number integer,
  github_pr_url text,
  github_head_sha text,
  github_merge_sha text,
  last_error_code text,
  deployment_requested_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  merged_at timestamptz,
  published_at timestamptz
);

create table public.publication_batch_items (
  batch_id uuid not null references public.publication_batches(id) on delete cascade,
  submission_id uuid not null references public.opportunity_submissions(id),
  listing_id text check (
    listing_id is null or listing_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
  ),
  created_at timestamptz not null default now(),
  primary key (batch_id, submission_id)
);

create index publication_batches_reconciliation
  on public.publication_batches (status, updated_at);
create index publication_batch_items_submission
  on public.publication_batch_items (submission_id);

create trigger publication_batches_touch_updated_at
before update on public.publication_batches
for each row execute function public.touch_updated_at();

create or replace function public.begin_publication_batch(
  p_moderator_id uuid
) returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_batch_id uuid;
  v_item_count integer;
begin
  if not exists (
    select 1 from public.moderator_profiles
    where user_id = p_moderator_id and role = 'admin' and active = true
  ) then
    raise exception 'administrator access required';
  end if;

  perform pg_advisory_xact_lock(hashtext('perkcommons-publication-batch'));

  select id into v_batch_id
  from public.publication_batches
  where status in ('preparing', 'validating', 'merging')
  order by created_at asc
  limit 1;
  if v_batch_id is not null then return v_batch_id; end if;

  insert into public.publication_batches (created_by)
  values (p_moderator_id)
  returning id into v_batch_id;

  insert into public.publication_batch_items (batch_id, submission_id)
  select v_batch_id, submissions.id
  from public.opportunity_submissions as submissions
  inner join public.normalized_opportunities as normalized
    on normalized.submission_id = submissions.id
  where submissions.status = 'approved'
  order by submissions.reviewed_at asc nulls last, submissions.created_at asc;
  get diagnostics v_item_count = row_count;

  if v_item_count = 0 then
    delete from public.publication_batches where id = v_batch_id;
    return null;
  end if;

  update public.publication_batches
  set item_count = v_item_count
  where id = v_batch_id;

  insert into public.moderation_actions (
    submission_id, moderator_id, action, reason, previous_status, new_status,
    metadata
  )
  select
    items.submission_id,
    p_moderator_id,
    'publication_queued',
    'Queued for validated PerkCommons/data publication',
    'approved',
    'approved',
    jsonb_build_object('publication_batch_id', v_batch_id)
  from public.publication_batch_items as items
  where items.batch_id = v_batch_id;
  return v_batch_id;
end;
$$;

create or replace function public.publication_batch_payload(
  p_batch_id uuid
) returns table (
  submission_id uuid,
  title text,
  organization text,
  primary_category text,
  subcategories text[],
  tags text[],
  description text,
  eligibility text,
  benefits text,
  location text,
  deadline date,
  source_url text,
  organization_website_url text
)
language sql
security definer
set search_path = ''
as $$
  select
    items.submission_id,
    normalized.title,
    normalized.organization,
    normalized.primary_category,
    normalized.subcategories,
    normalized.tags,
    normalized.description,
    normalized.eligibility,
    normalized.benefits,
    normalized.location,
    normalized.deadline,
    normalized.source_url,
    normalized.organization_website_url
  from public.publication_batch_items as items
  inner join public.normalized_opportunities as normalized
    on normalized.submission_id = items.submission_id
  where items.batch_id = p_batch_id
  order by normalized.organization, normalized.title, items.submission_id;
$$;

create or replace function public.finalize_publication_batch(
  p_batch_id uuid,
  p_merge_sha text
) returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_batch public.publication_batches%rowtype;
  v_count integer;
begin
  select * into v_batch
  from public.publication_batches
  where id = p_batch_id
  for update;
  if v_batch.id is null then raise exception 'publication batch not found'; end if;
  if v_batch.status = 'published' then return v_batch.item_count; end if;
  if v_batch.status not in ('validating', 'merging') then
    raise exception 'publication batch is not ready to finalize';
  end if;
  if exists (
    select 1 from public.publication_batch_items
    where batch_id = p_batch_id and listing_id is null
  ) then
    raise exception 'publication batch contains incomplete items';
  end if;

  insert into public.moderation_actions (
    submission_id, moderator_id, action, reason, previous_status, new_status,
    metadata
  )
  select
    submissions.id,
    v_batch.created_by,
    'publish',
    'Validated PerkCommons/data publication batch',
    submissions.status,
    'published',
    jsonb_build_object(
      'publication_batch_id', p_batch_id,
      'github_pr_number', v_batch.github_pr_number,
      'listing_id', items.listing_id,
      'merge_sha', p_merge_sha
    )
  from public.opportunity_submissions as submissions
  inner join public.publication_batch_items as items
    on items.submission_id = submissions.id
  where items.batch_id = p_batch_id and submissions.status = 'approved';

  update public.opportunity_submissions as submissions
  set status = 'published',
      published_at = now(),
      last_action_at = now()
  from public.publication_batch_items as items
  where items.batch_id = p_batch_id
    and items.submission_id = submissions.id
    and submissions.status = 'approved';
  get diagnostics v_count = row_count;

  update public.publication_batches
  set status = 'published',
      github_merge_sha = p_merge_sha,
      merged_at = coalesce(merged_at, now()),
      published_at = now(),
      last_error_code = null
  where id = p_batch_id;
  return v_count;
end;
$$;

alter table public.publication_batches enable row level security;
alter table public.publication_batch_items enable row level security;
revoke all on public.publication_batches, public.publication_batch_items
  from public, anon, authenticated;
revoke execute on function public.begin_publication_batch(uuid)
  from public, anon, authenticated;
revoke execute on function public.publication_batch_payload(uuid)
  from public, anon, authenticated;
revoke execute on function public.finalize_publication_batch(uuid, text)
  from public, anon, authenticated;
grant execute on function public.begin_publication_batch(uuid) to service_role;
grant execute on function public.publication_batch_payload(uuid) to service_role;
grant execute on function public.finalize_publication_batch(uuid, text)
  to service_role;

-- --------------------------------------------------------------------------
-- Squashed from supabase/migrations/202607190003_automated_listing_removal.sql
-- --------------------------------------------------------------------------
create table public.listing_removal_batches (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null unique references public.listing_reports(id),
  listing_id text not null unique
    check (listing_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  status text not null default 'preparing'
    check (status in ('preparing', 'validating', 'merging', 'removed', 'failed')),
  created_by uuid not null references auth.users(id),
  github_branch text,
  github_pr_number integer,
  github_pr_url text,
  github_head_sha text,
  github_merge_sha text,
  last_error_code text,
  deployment_requested_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  merged_at timestamptz,
  removed_at timestamptz
);

create index listing_removal_batches_reconciliation
  on public.listing_removal_batches (status, updated_at);

create trigger listing_removal_batches_touch_updated_at
before update on public.listing_removal_batches
for each row execute function public.touch_updated_at();

create or replace function public.resolve_listing_report(
  p_report_id uuid,
  p_moderator_id uuid,
  p_decision text,
  p_notes text default null
) returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_listing_id text;
  v_removal_batch_id uuid;
  v_removal_queued boolean := false;
begin
  if not exists (
    select 1 from public.moderator_profiles
    where user_id = p_moderator_id and active = true
  ) then
    raise exception 'moderator access required';
  end if;
  if p_decision not in ('upheld', 'dismissed') then
    raise exception 'invalid report decision';
  end if;

  select listing_id into v_listing_id
  from public.listing_reports
  where id = p_report_id and status in ('open', 'reviewing')
  for update;
  if v_listing_id is null then raise exception 'open report not found'; end if;

  update public.listing_reports
  set status = p_decision,
      assigned_to = p_moderator_id,
      resolution_notes = nullif(trim(p_notes), ''),
      resolved_at = now()
  where id = p_report_id;

  if p_decision = 'upheld' then
    insert into public.listing_moderation_state (
      listing_id, removed, removal_report_id, updated_by
    ) values (
      v_listing_id, true, p_report_id, p_moderator_id
    ) on conflict (listing_id) do update set
      removed = true,
      removal_report_id = excluded.removal_report_id,
      updated_by = excluded.updated_by,
      updated_at = now();

    insert into public.listing_removal_batches (
      report_id, listing_id, created_by
    ) values (
      p_report_id, v_listing_id, p_moderator_id
    ) on conflict (listing_id) do nothing
    returning id into v_removal_batch_id;
    v_removal_queued := v_removal_batch_id is not null;

    if v_removal_batch_id is null then
      select id into v_removal_batch_id
      from public.listing_removal_batches
      where listing_id = v_listing_id;
    end if;
  end if;

  insert into public.moderation_actions (
    moderator_id, action, reason, notes, metadata
  ) values (
    p_moderator_id,
    case when p_decision = 'upheld' then 'report_upheld' else 'report_dismissed' end,
    p_decision,
    nullif(trim(p_notes), ''),
    jsonb_strip_nulls(jsonb_build_object(
      'report_id', p_report_id,
      'listing_id', v_listing_id,
      'removal_batch_id', v_removal_batch_id
    ))
  );

  if v_removal_queued then
    insert into public.moderation_actions (
      moderator_id, action, reason, metadata
    ) values (
      p_moderator_id,
      'listing_removal_queued',
      'Queued for validated PerkCommons/data removal',
      jsonb_build_object(
        'report_id', p_report_id,
        'listing_id', v_listing_id,
        'removal_batch_id', v_removal_batch_id
      )
    );
  end if;

  return v_listing_id;
end;
$$;

create or replace function public.finalize_listing_removal_batch(
  p_batch_id uuid,
  p_merge_sha text
) returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_batch public.listing_removal_batches%rowtype;
begin
  select * into v_batch
  from public.listing_removal_batches
  where id = p_batch_id
  for update;
  if v_batch.id is null then raise exception 'listing removal batch not found'; end if;
  if v_batch.status = 'removed' then return v_batch.listing_id; end if;
  if v_batch.status not in ('preparing', 'validating', 'merging') then
    raise exception 'listing removal batch is not ready to finalize';
  end if;

  update public.listing_moderation_state
  set removed = true,
      featured = false,
      updated_by = v_batch.created_by,
      updated_at = now()
  where listing_id = v_batch.listing_id;

  insert into public.moderation_actions (
    moderator_id, action, reason, metadata
  ) values (
    v_batch.created_by,
    'listing_removed_from_data',
    'Validated PerkCommons/data removal',
    jsonb_strip_nulls(jsonb_build_object(
      'report_id', v_batch.report_id,
      'listing_id', v_batch.listing_id,
      'removal_batch_id', v_batch.id,
      'github_pr_number', v_batch.github_pr_number,
      'merge_sha', p_merge_sha
    ))
  );

  update public.listing_removal_batches
  set status = 'removed',
      github_merge_sha = p_merge_sha,
      merged_at = coalesce(merged_at, now()),
      removed_at = now(),
      last_error_code = null
  where id = p_batch_id;
  return v_batch.listing_id;
end;
$$;

-- Queue reports upheld before this migration so existing suppressed listings
-- are also removed from the Git-owned public dataset.
insert into public.listing_removal_batches (
  report_id, listing_id, created_by
)
select reports.id, reports.listing_id, reports.assigned_to
from public.listing_reports as reports
inner join public.listing_moderation_state as state
  on state.listing_id = reports.listing_id and state.removed = true
where reports.status = 'upheld'
  and reports.assigned_to is not null
on conflict (listing_id) do nothing;

alter table public.listing_removal_batches enable row level security;
revoke all on public.listing_removal_batches from public, anon, authenticated;
revoke execute on function public.finalize_listing_removal_batch(uuid, text)
  from public, anon, authenticated;
grant execute on function public.finalize_listing_removal_batch(uuid, text)
  to service_role;

-- --------------------------------------------------------------------------
-- Squashed from supabase/migrations/202607220001_next_review_concurrency.sql
-- --------------------------------------------------------------------------
-- Experimental fork migration. Apply only to an isolated development project.
alter table public.opportunity_submissions
  add column if not exists assigned_moderator uuid references auth.users(id) on delete set null,
  add column if not exists claimed_at timestamptz,
  add column if not exists review_started_at timestamptz,
  add column if not exists revision bigint not null default 0,
  add column if not exists second_review_required boolean not null default false,
  add column if not exists second_reviewer uuid references auth.users(id) on delete set null,
  add column if not exists second_reviewed_at timestamptz,
  add column if not exists conflict_of_interest boolean not null default false;

alter table public.opportunity_submissions
  drop constraint if exists opportunity_submissions_distinct_reviewers;
alter table public.opportunity_submissions
  add constraint opportunity_submissions_distinct_reviewers
  check (second_reviewer is null or reviewed_by is null or second_reviewer <> reviewed_by);

create or replace function public.bump_submission_revision()
returns trigger language plpgsql as $$
begin
  new.revision = old.revision + 1;
  return new;
end;
$$;

drop trigger if exists opportunity_submissions_bump_revision on public.opportunity_submissions;
create trigger opportunity_submissions_bump_revision
before update on public.opportunity_submissions
for each row execute function public.bump_submission_revision();

create or replace function public.claim_submission(
  p_submission_id uuid,
  p_moderator_id uuid,
  p_expected_revision bigint
) returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_submission public.opportunity_submissions%rowtype;
begin
  if not exists (
    select 1 from public.moderator_profiles
    where user_id = p_moderator_id and active = true
  ) then raise exception 'moderator access required'; end if;

  select * into v_submission
  from public.opportunity_submissions
  where id = p_submission_id
  for update;
  if v_submission.id is null then raise exception 'submission not found'; end if;
  if v_submission.revision <> p_expected_revision then raise exception 'stale revision'; end if;
  if v_submission.assigned_moderator is not null and v_submission.assigned_moderator <> p_moderator_id then
    raise exception 'submission already claimed';
  end if;

  update public.opportunity_submissions
  set assigned_moderator = p_moderator_id,
      claimed_at = coalesce(claimed_at, now()),
      review_started_at = coalesce(review_started_at, now()),
      status = case when status = 'pending' then 'reviewing' else status end
  where id = p_submission_id
  returning revision into v_submission.revision;
  return v_submission.revision;
end;
$$;

create or replace function public.complete_second_review(
  p_submission_id uuid,
  p_moderator_id uuid,
  p_expected_revision bigint
) returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_submission public.opportunity_submissions%rowtype;
begin
  if not exists (
    select 1 from public.moderator_profiles
    where user_id = p_moderator_id and active = true
  ) then raise exception 'moderator access required'; end if;

  select * into v_submission
  from public.opportunity_submissions
  where id = p_submission_id
  for update;
  if v_submission.id is null then raise exception 'submission not found'; end if;
  if v_submission.revision <> p_expected_revision then raise exception 'stale revision'; end if;
  if not v_submission.second_review_required then raise exception 'second review is not required'; end if;
  if v_submission.reviewed_by is null then raise exception 'first review is incomplete'; end if;
  if v_submission.reviewed_by = p_moderator_id then raise exception 'second reviewer must be independent'; end if;
  if v_submission.conflict_of_interest then raise exception 'conflict of interest requires escalation'; end if;

  update public.opportunity_submissions
  set second_reviewer = p_moderator_id,
      second_reviewed_at = now()
  where id = p_submission_id
  returning revision into v_submission.revision;

  insert into public.moderation_actions (
    submission_id, moderator_id, action, reason, previous_status, new_status,
    metadata
  ) values (
    p_submission_id, p_moderator_id, 'second_review',
    'Independent second review completed', v_submission.status, v_submission.status,
    jsonb_build_object('expected_revision', p_expected_revision)
  );
  return v_submission.revision;
end;
$$;

revoke execute on function public.claim_submission(uuid, uuid, bigint) from public, anon, authenticated;
revoke execute on function public.complete_second_review(uuid, uuid, bigint) from public, anon, authenticated;
grant execute on function public.claim_submission(uuid, uuid, bigint) to service_role;
grant execute on function public.complete_second_review(uuid, uuid, bigint) to service_role;

-- --------------------------------------------------------------------------
-- Squashed from supabase/migrations/202607220002_publication_semantics.sql
-- --------------------------------------------------------------------------
-- This migration is intentionally additive. Existing approved rows remain
-- incomplete until a moderator explicitly reviews the new semantic fields.
alter table public.normalized_opportunities
  add column if not exists resource_type text,
  add column if not exists default_search_eligible boolean,
  add column if not exists availability_status text,
  add column if not exists status_reason text,
  add column if not exists deadline_type text,
  add column if not exists global boolean,
  add column if not exists remote boolean,
  add column if not exists countries text[] not null default '{}',
  add column if not exists physical_locations text[] not null default '{}',
  add column if not exists provider_url text,
  add column if not exists program_url text,
  add column if not exists application_url text,
  add column if not exists sponsored boolean,
  add column if not exists sponsorship_type text,
  add column if not exists sponsorship_disclosure text,
  add column if not exists claims_checked text[] not null default '{}',
  add column if not exists next_review_at date;

alter table public.normalized_opportunities
  drop constraint if exists normalized_opportunities_resource_type_check,
  drop constraint if exists normalized_opportunities_availability_status_check,
  drop constraint if exists normalized_opportunities_deadline_type_check,
  drop constraint if exists normalized_opportunities_countries_check,
  drop constraint if exists normalized_opportunities_sponsorship_check,
  drop constraint if exists normalized_opportunities_claims_checked_check;

alter table public.normalized_opportunities
  add constraint normalized_opportunities_resource_type_check check (
    resource_type is null or resource_type in (
      'opportunity', 'resource', 'benefit', 'program', 'event', 'funding',
      'fellowship', 'competition', 'community', 'learning-resource',
      'public-dataset', 'general-free-product'
    )
  ),
  add constraint normalized_opportunities_availability_status_check check (
    availability_status is null or availability_status in (
      'open', 'rolling', 'upcoming', 'limited', 'waitlist',
      'temporarily-unavailable', 'closed', 'expired', 'unconfirmed',
      'disputed', 'archived'
    )
  ),
  add constraint normalized_opportunities_deadline_type_check check (
    deadline_type is null or deadline_type in ('fixed', 'rolling', 'periodic', 'unknown', 'none')
  ),
  add constraint normalized_opportunities_countries_check check (
    cardinality(countries) <= 30 and (
      cardinality(countries) = 0 or array_to_string(countries, ',') ~ '^[A-Z]{2}(,[A-Z]{2})*$'
    )
  ),
  add constraint normalized_opportunities_sponsorship_check check (
    sponsored is distinct from true or (
      nullif(btrim(sponsorship_type), '') is not null and
      nullif(btrim(sponsorship_disclosure), '') is not null
    )
  ),
  add constraint normalized_opportunities_claims_checked_check check (
    claims_checked <@ array[
      'program-exists', 'eligibility', 'benefit', 'application-url', 'deadline', 'geography'
    ]::text[]
  );

create or replace function public.perform_moderation_action(
  p_submission_id uuid,
  p_moderator_id uuid,
  p_action text,
  p_reason text default null,
  p_notes text default null,
  p_normalized jsonb default null
) returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role text;
  v_previous text;
  v_next text;
  v_action_id uuid;
begin
  select role into v_role from public.moderator_profiles
  where user_id = p_moderator_id and active = true;
  if v_role is null then raise exception 'moderator access required'; end if;

  select status::text into v_previous from public.opportunity_submissions
  where id = p_submission_id for update;
  if v_previous is null then raise exception 'submission not found'; end if;

  v_next := case p_action
    when 'approve' then 'approved'
    when 'decline' then 'rejected'
    when 'flag' then 'flagged'
    when 'unflag' then 'pending'
    when 'publish' then 'published'
    when 'withdraw' then 'withdrawn'
    else v_previous
  end;

  if p_action not in ('approve', 'decline', 'flag', 'unflag', 'publish', 'withdraw', 'note', 'edit') then
    raise exception 'unsupported moderation action';
  end if;

  update public.opportunity_submissions
  set status = v_next,
      reviewed_by = p_moderator_id,
      decision_reason = case when p_action in ('approve', 'decline') then p_reason else decision_reason end,
      reviewed_at = case when p_action in ('approve', 'decline') then now() else reviewed_at end,
      published_at = case when p_action = 'publish' then now() else published_at end,
      last_action_at = now(),
      flag_count = case when p_action = 'flag' then flag_count + 1 when p_action = 'unflag' then 0 else flag_count end
  where id = p_submission_id;

  if p_action = 'flag' then
    insert into public.submission_flags (submission_id, reason, notes, moderator_id)
    values (p_submission_id, coalesce(p_reason, 'Other'), p_notes, p_moderator_id);
  elsif p_action = 'unflag' then
    update public.submission_flags
    set resolved = true, resolved_by = p_moderator_id, resolved_at = now()
    where submission_id = p_submission_id and resolved = false;
  end if;

  if p_action = 'approve' and p_normalized is not null then
    insert into public.normalized_opportunities (
      submission_id, title, organization, categories, primary_category,
      subcategories, tags, description, eligibility, benefits, location,
      deadline, source_url, organization_website_url, resource_type, default_search_eligible,
      availability_status, status_reason, deadline_type, global, remote,
      countries, physical_locations, provider_url, program_url,
      application_url, sponsored, sponsorship_type,
      sponsorship_disclosure, claims_checked, next_review_at, normalized_by
    ) values (
      p_submission_id, p_normalized->>'title', p_normalized->>'organization',
      coalesce(array(select jsonb_array_elements_text(p_normalized->'categories')), '{}'),
      p_normalized->>'primary_category',
      coalesce(array(select jsonb_array_elements_text(p_normalized->'subcategories')), '{}'),
      coalesce(array(select jsonb_array_elements_text(p_normalized->'tags')), '{}'),
      p_normalized->>'description', p_normalized->>'eligibility', p_normalized->>'benefits',
      p_normalized->>'location', nullif(p_normalized->>'deadline', '')::date,
      p_normalized->>'source_url', p_normalized->>'organization_website_url',
      p_normalized->>'resource_type', (p_normalized->>'default_search_eligible')::boolean,
      p_normalized->>'availability_status',
      p_normalized->>'status_reason', p_normalized->>'deadline_type',
      nullif(p_normalized->>'global', '')::boolean,
      nullif(p_normalized->>'remote', '')::boolean,
      coalesce(array(select jsonb_array_elements_text(p_normalized->'countries')), '{}'),
      coalesce(array(select jsonb_array_elements_text(p_normalized->'physical_locations')), '{}'),
      p_normalized->>'provider_url', p_normalized->>'program_url',
      p_normalized->>'application_url', nullif(p_normalized->>'sponsored', '')::boolean,
      p_normalized->>'sponsorship_type', p_normalized->>'sponsorship_disclosure',
      coalesce(array(select jsonb_array_elements_text(p_normalized->'claims_checked')), '{}'),
      nullif(p_normalized->>'next_review_at', '')::date, p_moderator_id
    ) on conflict (submission_id) do update set
      title = excluded.title,
      organization = excluded.organization,
      categories = excluded.categories,
      primary_category = excluded.primary_category,
      subcategories = excluded.subcategories,
      tags = excluded.tags,
      description = excluded.description,
      eligibility = excluded.eligibility,
      benefits = excluded.benefits,
      location = excluded.location,
      deadline = excluded.deadline,
      source_url = excluded.source_url,
      organization_website_url = excluded.organization_website_url,
      resource_type = excluded.resource_type,
      default_search_eligible = excluded.default_search_eligible,
      availability_status = excluded.availability_status,
      status_reason = excluded.status_reason,
      deadline_type = excluded.deadline_type,
      global = excluded.global,
      remote = excluded.remote,
      countries = excluded.countries,
      physical_locations = excluded.physical_locations,
      provider_url = excluded.provider_url,
      program_url = excluded.program_url,
      application_url = excluded.application_url,
      sponsored = excluded.sponsored,
      sponsorship_type = excluded.sponsorship_type,
      sponsorship_disclosure = excluded.sponsorship_disclosure,
      claims_checked = excluded.claims_checked,
      next_review_at = excluded.next_review_at,
      normalized_by = excluded.normalized_by,
      updated_at = now();
  end if;

  insert into public.moderation_actions (
    submission_id, moderator_id, action, reason, notes, previous_status, new_status, metadata
  ) values (
    p_submission_id, p_moderator_id, p_action, p_reason, p_notes, v_previous, v_next,
    case when p_normalized is null then '{}'::jsonb else jsonb_build_object(
      'normalized_fields', true,
      'resource_type', p_normalized->>'resource_type',
      'default_search_eligible', p_normalized->>'default_search_eligible',
      'availability_status', p_normalized->>'availability_status',
      'claims_checked', p_normalized->'claims_checked'
    ) end
  ) returning id into v_action_id;
  return v_action_id;
end;
$$;

drop function if exists public.publication_batch_payload(uuid);
create function public.publication_batch_payload(
  p_batch_id uuid
) returns table (
  submission_id uuid,
  title text,
  organization text,
  primary_category text,
  subcategories text[],
  tags text[],
  description text,
  eligibility text,
  benefits text,
  resource_type text,
  default_search_eligible boolean,
  availability_status text,
  status_reason text,
  deadline_type text,
  deadline date,
  global boolean,
  remote boolean,
  countries text[],
  physical_locations text[],
  provider_url text,
  program_url text,
  application_url text,
  sponsored boolean,
  sponsorship_type text,
  sponsorship_disclosure text,
  claims_checked text[],
  next_review_at date,
  normalized_at timestamptz
)
language sql
security definer
set search_path = ''
as $$
  select
    items.submission_id,
    normalized.title,
    normalized.organization,
    normalized.primary_category,
    normalized.subcategories,
    normalized.tags,
    normalized.description,
    normalized.eligibility,
    normalized.benefits,
    normalized.resource_type,
    normalized.default_search_eligible,
    normalized.availability_status,
    normalized.status_reason,
    normalized.deadline_type,
    normalized.deadline,
    normalized.global,
    normalized.remote,
    normalized.countries,
    normalized.physical_locations,
    normalized.provider_url,
    normalized.program_url,
    normalized.application_url,
    normalized.sponsored,
    normalized.sponsorship_type,
    normalized.sponsorship_disclosure,
    normalized.claims_checked,
    normalized.next_review_at,
    normalized.updated_at
  from public.publication_batch_items as items
  inner join public.normalized_opportunities as normalized
    on normalized.submission_id = items.submission_id
  where items.batch_id = p_batch_id
  order by normalized.organization, normalized.title, items.submission_id;
$$;

revoke execute on function public.perform_moderation_action(uuid, uuid, text, text, text, jsonb)
  from public, anon, authenticated;
grant execute on function public.perform_moderation_action(uuid, uuid, text, text, text, jsonb)
  to service_role;
revoke execute on function public.publication_batch_payload(uuid)
  from public, anon, authenticated;
grant execute on function public.publication_batch_payload(uuid) to service_role;

-- Final greenfield-only hardening and compatibility.
drop trigger if exists opportunity_submissions_touch_updated_at
  on public.opportunity_submissions;
create trigger opportunity_submissions_touch_updated_at
before update on public.opportunity_submissions
for each row execute function public.touch_updated_at();

grant usage on schema public to service_role;
grant all privileges on all tables in schema public to service_role;
grant all privileges on all sequences in schema public to service_role;

-- Browser roles receive no direct access to private workflow tables. Public
-- intake and moderator operations go through the fork Worker with service-role
-- isolation and explicit RPC grants.
revoke all privileges on all tables in schema public from anon, authenticated;
revoke all privileges on all sequences in schema public from anon, authenticated;

commit;
