/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=dev --include-runtime=false worker/worker-configuration.d.ts` (hash: 72a8b5966ede199c68b0e28fe972a6f1)
interface __BaseEnv_Env {
	SUBMISSION_RATE_LIMITER: RateLimit;
	REPORT_RATE_LIMITER: RateLimit;
	LOGIN_RATE_LIMITER: RateLimit;
	TRACKING_RATE_LIMITER: RateLimit;
	ENVIRONMENT: "test";
	SUPABASE_URL: string;
	SUPABASE_PUBLISHABLE_KEY: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	SUBMISSION_FINGERPRINT_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY" | "SUPABASE_SERVICE_ROLE_KEY" | "SUBMISSION_FINGERPRINT_SECRET">> {}
}
